#!/usr/bin/env bash

# Function to check and print factors
calculate_and_print_factors()
{
	if [ $# -ne 3 ];
	then
		factor_array=("$@")
		index=0
		factor_product=1
		for factor in ${factor_array[*]};
		do
			if [ $index -gt 1 ];
			then
				factor_product=$(echo $factor*$factor_product | bc)
			fi
			index=$((index + 1))
		done
	else
		factor_product=$3
	fi

	original_num=$2
	num=$(echo "$1" | tr ':' '=')

	comparison=$(echo "if($factor_product > $original_num) 1 else 0" | bc)
	if ((comparison == 1)); then
		temp_var=$original_num
		original_num=$factor_product
		factor_product=$temp_var
	fi

	echo "$num$original_num*$factor_product"
}

if [ $# -ne 1 ]
then
	echo 'Usage: factors <file>'
	exit 1
else

	while read line_from_file
	do

		factor_output=$(factor "$line_from_file")
		calculate_and_print_factors $factor_output

	done < "$1"
fi

