#!/usr/bin/env bash
# RSA Factoring Challenge challenge by sebsibe solomon

evaluate_factor()
{
	if [ $# -ne 3 ];
	then
		parameters=("$@")
		index=0
		product=1
		for param in ${parameters[*]};
		do
			if [ $index -gt 1 ];
			then
				product=$(echo $param*$product | bc)
			fi
			index=$((index + 1))
		done
	else
		product=$3
	fi

	original=$2
	number=$(echo "$1" | tr ':' '=')

	comparison=$(echo "if($product > $original) 1 else 0" | bc)
	if ((comparison == 1)); then
		temp=$original
		original=$product
		product=$temp
	fi

	echo "$number$original*$product"
}

if [ $# -ne 1 ]
then
	echo 'Usage: rsa <file>'
	exit 1
else

	while read line
	do

		factor_result=$(factor "$line")
		evaluate_factor $factor_result

	done < "$1"
fi

